Michelle usersignup
chris-befoul/cs467_capstone pull request #15
Opened 2022-02-17 05:06 UTC by liumiche

2022-02-17 06:59 UTC, vincentchen137 approved these changes

2022-02-17 19:35 UTC, chris-befoul requested changes
With the way the logic is set up here only the last image submitted will be saved in datastore. Also there is no need to save the image in datastore, with the way images are saved in cloud storage it is done so as a folder <pet_id>/<file_name>. If you have the pet ID you can call cloud storage to list out all image files that match that pet ID. I have also already implemented a delete photo from image function within my petPhoto.js

2022-02-17 23:17 UTC, vincentchen137 approved these changes

2022-02-17 23:38 UTC, liumiche commented
> 

I totally forgot about the petsPhotos function you wrote when I was doing this. Just updated the logic to remove image from Datastore.

2022-02-18 01:43 UTC, chris-befoul approved these changes

2022-02-18 01:44 UTC, merged